-- Diek Abriss – Datenbank & Storage
-- Einmal im Supabase SQL Editor ausführen. Bestehende id/created_at Spalten bleiben erhalten.

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  email text,
  location text,
  service text not null,
  object_type text,
  disposal boolean not null default false,
  disposal_items text,
  message text not null,
  photo_paths jsonb not null default '[]'::jsonb,
  status text not null default 'Neu'
);

alter table public.contact_requests enable row level security;

alter table public.contact_requests add column if not exists name text;
alter table public.contact_requests add column if not exists phone text;
alter table public.contact_requests add column if not exists email text;
alter table public.contact_requests add column if not exists location text;
alter table public.contact_requests add column if not exists service text;
alter table public.contact_requests add column if not exists object_type text;
alter table public.contact_requests add column if not exists disposal boolean not null default false;
alter table public.contact_requests add column if not exists disposal_items text;
alter table public.contact_requests add column if not exists message text;
alter table public.contact_requests add column if not exists photo_paths jsonb not null default '[]'::jsonb;
alter table public.contact_requests add column if not exists status text not null default 'Neu';

drop policy if exists "Public can create requests" on public.contact_requests;
create policy "Public can create requests" on public.contact_requests
for insert to anon, authenticated
with check (true);

drop policy if exists "Staff can read requests" on public.contact_requests;
create policy "Staff can read requests" on public.contact_requests
for select to authenticated using (true);

drop policy if exists "Staff can update requests" on public.contact_requests;
create policy "Staff can update requests" on public.contact_requests
for update to authenticated using (true) with check (true);

drop policy if exists "Staff can delete requests" on public.contact_requests;
create policy "Staff can delete requests" on public.contact_requests
for delete to authenticated using (true);

-- Öffentliche Website-Einstellungen. Besucher dürfen die aktuellen Werte lesen,
-- aber ausschließlich angemeldete Mitarbeiter dürfen sie verändern.
create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;

insert into public.site_settings (key, value)
values (
  'site',
  '{
    "hero": {
      "title_1": "RAUS DAMIT.",
      "title_2": "SAUBER FERTIG.",
      "lead": "Diek Abriss räumt, baut zurück, entsorgt und schafft Platz. Direkt, zuverlässig und mit sauberer Übergabe."
    },
    "contact": {
      "phone": "0163 1769483",
      "email": "info@diek-abriss.de",
      "whatsapp": "491631769483"
    },
    "area": {
      "title": "Augsburg & Umgebung",
      "lead": "Wir sind in Augsburg und vielen Orten in der Umgebung unterwegs.",
      "cities": ["Augsburg", "Aichach", "Königsbrunn", "Mering", "Friedberg", "Gersthofen", "Neusäß", "Stadtbergen", "Bobingen", "Kissing", "Diedorf", "Schwabmünchen", "Meitingen", "Landsberg am Lech", "Fürstenfeldbruck", "Dachau", "Wertingen", "Günzburg", "Burgau", "Thannhausen", "Mindelheim"]
    },
    "faq": [
      {"question": "Welche Arbeiten übernehmen Sie?", "answer": "Wir unterstützen bei Abriss, Entrümpelung, Demontage, Rückbau und Entsorgung – für Wohnungen, Häuser, Keller, Gärten, Gewerbe und Baustellen."},
      {"question": "Wie kann ich eine Anfrage stellen?", "answer": "Sie können das Anfrageformular nutzen, uns anrufen oder direkt per WhatsApp schreiben. Fotos helfen uns bei einer schnellen Einschätzung."},
      {"question": "Kann ich Fotos mit meiner Anfrage senden?", "answer": "Ja. Sie können direkt mit der Kamera ein Foto aufnehmen oder bis zu zehn Fotos aus Ihrer Galerie beziehungsweise Ihren Dateien auswählen."},
      {"question": "Übernehmen Sie auch die Entsorgung?", "answer": "Ja. Wenn Sie Entsorgung auswählen, berücksichtigen wir den Abtransport und die fachgerechte Entsorgung in der Einschätzung."},
      {"question": "In welchem Gebiet sind Sie tätig?", "answer": "Wir sind in Augsburg und vielen Orten in der Umgebung unterwegs. Die aktuellen Einsatzorte finden Sie direkt auf dieser Seite."}
    ],
    "pricing": {
      "base": 400,
      "object": {"wohnung": 0, "keller": 150, "haus": 300, "gewerbe": 250, "garten": 200},
      "work": {"abriss": 0, "entsorgung": 0, "entruempelung": 0, "demontage": 0, "rueckbau": 0, "komplettpaket": 0},
      "size": {"klein": 250, "mittel": 500, "gross": 850, "sehr_gross": 1300},
      "disposal": {"nein": 0, "ja": 180},
      "waste": {"moebel": 0, "sperrmuell": 80, "holz": 140, "bauschutt": 220, "gartenabfaelle": 120, "gemischt": 250, "sonstiges": 0}
    }
  }'::jsonb
)
on conflict (key) do nothing;

-- Bei einer bestehenden Installation ergänzt dieser Schritt nur die neue FAQ,
-- ohne bereits gepflegte Kontakt-, Einsatzgebiet- oder Preisangaben zu ändern.
update public.site_settings
set value = jsonb_set(
  value,
  '{faq}',
  '[{"question":"Welche Arbeiten übernehmen Sie?","answer":"Wir unterstützen bei Abriss, Entrümpelung, Demontage, Rückbau und Entsorgung – für Wohnungen, Häuser, Keller, Gärten, Gewerbe und Baustellen."},{"question":"Wie kann ich eine Anfrage stellen?","answer":"Sie können das Anfrageformular nutzen, uns anrufen oder direkt per WhatsApp schreiben. Fotos helfen uns bei einer schnellen Einschätzung."},{"question":"Kann ich Fotos mit meiner Anfrage senden?","answer":"Ja. Sie können direkt mit der Kamera ein Foto aufnehmen oder bis zu zehn Fotos aus Ihrer Galerie beziehungsweise Ihren Dateien auswählen."},{"question":"Übernehmen Sie auch die Entsorgung?","answer":"Ja. Wenn Sie Entsorgung auswählen, berücksichtigen wir den Abtransport und die fachgerechte Entsorgung in der Einschätzung."},{"question":"In welchem Gebiet sind Sie tätig?","answer":"Wir sind in Augsburg und vielen Orten in der Umgebung unterwegs. Die aktuellen Einsatzorte finden Sie direkt auf dieser Seite."}]'::jsonb,
  true
)
where key = 'site' and not (value ? 'faq');

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings" on public.site_settings
for select to anon, authenticated
using (key = 'site');

drop policy if exists "Staff can update site settings" on public.site_settings;
create policy "Staff can update site settings" on public.site_settings
for update to authenticated
using (key = 'site')
with check (key = 'site');

-- Storage: Der Bucket wird hier angelegt bzw. auf die benötigten Upload-Regeln
-- eingestellt. Damit ist die Einrichtung nicht mehr von einem manuellen Schritt
-- im Storage-Dashboard abhängig.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'diek-abriss-fotos',
  'diek-abriss-fotos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
on conflict (id) do update set
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/heic'];

-- Erlaubt öffentlichen Formularen das Hochladen, aber nur eingeloggtem Personal
-- das Lesen. Der erste Ordner muss die Anfrage-ID sein; so bleiben die Fotos
-- sauber einer Anfrage zugeordnet.
drop policy if exists "Public can upload diek photos" on storage.objects;
drop policy if exists "Kunden dürfen Fotos hochladen" on storage.objects;
create policy "Public can upload diek photos"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'diek-abriss-fotos'
  and (storage.foldername(name))[1] ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
);

drop policy if exists "Staff can read diek photos" on storage.objects;
create policy "Staff can read diek photos" on storage.objects
for select to authenticated
using (bucket_id = 'diek-abriss-fotos');

drop policy if exists "Staff can delete diek photos" on storage.objects;
create policy "Staff can delete diek photos" on storage.objects
for delete to authenticated
using (bucket_id = 'diek-abriss-fotos');
