-- Diek Abriss – Datenbank & Storage
-- Einmal im Supabase SQL Editor ausführen. Bestehende id/created_at Spalten bleiben erhalten.

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  email text,
  location text,
  service text not null,
  object_type text,
  disposal boolean not null default false,
  disposal_items text,
  message text not null,
  photo_paths jsonb not null default '[]'::jsonb,
  status text not null default 'Neu'
);

alter table public.contact_requests enable row level security;

alter table public.contact_requests add column if not exists name text;
alter table public.contact_requests add column if not exists phone text;
alter table public.contact_requests add column if not exists email text;
alter table public.contact_requests add column if not exists location text;
alter table public.contact_requests add column if not exists service text;
alter table public.contact_requests add column if not exists object_type text;
alter table public.contact_requests add column if not exists disposal boolean not null default false;
alter table public.contact_requests add column if not exists disposal_items text;
alter table public.contact_requests add column if not exists message text;
alter table public.contact_requests add column if not exists photo_paths jsonb not null default '[]'::jsonb;
alter table public.contact_requests add column if not exists status text not null default 'Neu';

drop policy if exists "Public can create requests" on public.contact_requests;
create policy "Public can create requests" on public.contact_requests
for insert to anon, authenticated
with check (true);

drop policy if exists "Staff can read requests" on public.contact_requests;
create policy "Staff can read requests" on public.contact_requests
for select to authenticated using (true);

drop policy if exists "Staff can update requests" on public.contact_requests;
create policy "Staff can update requests" on public.contact_requests
for update to authenticated using (true) with check (true);

drop policy if exists "Staff can delete requests" on public.contact_requests;
create policy "Staff can delete requests" on public.contact_requests
for delete to authenticated using (true);

-- Storage: Der Bucket wird hier angelegt bzw. auf die benötigten Upload-Regeln
-- eingestellt. Damit ist die Einrichtung nicht mehr von einem manuellen Schritt
-- im Storage-Dashboard abhängig.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'diek-abriss-fotos',
  'diek-abriss-fotos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
on conflict (id) do update set
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/heic'];

-- Erlaubt öffentlichen Formularen das Hochladen, aber nur eingeloggtem Personal
-- das Lesen. Der erste Ordner muss die Anfrage-ID sein; so bleiben die Fotos
-- sauber einer Anfrage zugeordnet.
drop policy if exists "Public can upload diek photos" on storage.objects;
drop policy if exists "Kunden dürfen Fotos hochladen" on storage.objects;
create policy "Public can upload diek photos"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'diek-abriss-fotos'
  and (storage.foldername(name))[1] ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
);

drop policy if exists "Staff can read diek photos" on storage.objects;
create policy "Staff can read diek photos" on storage.objects
for select to authenticated
using (bucket_id = 'diek-abriss-fotos');

drop policy if exists "Staff can delete diek photos" on storage.objects;
create policy "Staff can delete diek photos" on storage.objects
for delete to authenticated
using (bucket_id = 'diek-abriss-fotos');
